// Native Unicode keeps emoji available offline without fetching third-party images.
export const emojiGroups = [
  {
    name: 'Caras',
    items: [
      ['😀', 'sonrisa feliz'],
      ['😃', 'alegría feliz'],
      ['😄', 'risa feliz'],
      ['😁', 'sonrisa dientes'],
      ['😆', 'carcajada'],
      ['😅', 'risa nerviosa sudor'],
      ['😂', 'lágrimas risa'],
      ['🤣', 'carcajada suelo'],
      ['🙂', 'sonrisa leve'],
      ['🙃', 'cara invertida'],
      ['😉', 'guiño'],
      ['😊', 'sonrisa tímida'],
      ['🥰', 'amor corazones'],
      ['😍', 'enamorado'],
      ['🤩', 'estrellas emoción'],
      ['😘', 'beso'],
      ['😋', 'rico delicioso'],
      ['😛', 'lengua'],
      ['😜', 'guiño lengua'],
      ['🤪', 'locura'],
      ['🤔', 'pensando duda'],
      ['🤨', 'ceja sospecha'],
      ['😐', 'neutral'],
      ['😶', 'sin palabras'],
      ['🙄', 'ojos arriba'],
      ['😏', 'sonrisa pícara'],
      ['😴', 'dormido sueño'],
      ['🥱', 'bostezo'],
      ['😎', 'gafas sol genial'],
      ['🤓', 'nerd programador'],
      ['🧐', 'investigar monóculo'],
      ['🤯', 'sorpresa mente'],
      ['😮', 'sorprendido'],
      ['😱', 'miedo grito'],
      ['😢', 'triste lágrima'],
      ['😭', 'llanto'],
      ['🥺', 'por favor súplica'],
      ['😤', 'frustración'],
      ['😡', 'enojado'],
      ['🤬', 'furioso'],
      ['🤒', 'enfermo fiebre'],
      ['🤕', 'herido'],
      ['🤢', 'náusea'],
      ['🤧', 'estornudo'],
      ['🥳', 'fiesta celebrar'],
      ['🤗', 'abrazo'],
      ['🤭', 'risa tapada'],
      ['🫡', 'saludo militar'],
    ],
  },
  {
    name: 'Gestos',
    items: [
      ['👍', 'pulgar arriba bien ok', true],
      ['👎', 'pulgar abajo mal', true],
      ['👏', 'aplauso', true],
      ['🙌', 'celebrar manos arriba', true],
      ['👋', 'saludar hola adiós', true],
      ['🤚', 'mano parar', true],
      ['✋', 'alto mano', true],
      ['👌', 'perfecto ok', true],
      ['🤌', 'dedos juntos', true],
      ['🤏', 'pequeño poquito', true],
      ['✌️', 'victoria paz', true],
      ['🤞', 'suerte dedos cruzados', true],
      ['🤟', 'te quiero mano', true],
      ['🤘', 'rock', true],
      ['🤙', 'llámame', true],
      ['👈', 'izquierda', true],
      ['👉', 'derecha', true],
      ['👆', 'arriba', true],
      ['👇', 'abajo', true],
      ['☝️', 'índice atención', true],
      ['✊', 'puño', true],
      ['👊', 'chocar puños', true],
      ['🙏', 'gracias oración por favor', true],
      ['💪', 'fuerza músculo', true],
      ['🫶', 'manos corazón', true],
      ['🤝', 'acuerdo manos'],
      ['👀', 'ojos mirando'],
      ['🧠', 'cerebro idea'],
      ['🧑‍💻', 'programador código'],
    ],
  },
  {
    name: 'Corazones',
    items: [
      ['💜', 'corazón morado'],
      ['❤️', 'corazón rojo amor'],
      ['🧡', 'corazón naranja'],
      ['💛', 'corazón amarillo'],
      ['💚', 'corazón verde'],
      ['💙', 'corazón azul'],
      ['🩷', 'corazón rosa'],
      ['🤍', 'corazón blanco'],
      ['🖤', 'corazón negro'],
      ['🤎', 'corazón café'],
      ['💔', 'corazón roto'],
      ['💕', 'dos corazones'],
      ['💖', 'corazón brillante'],
      ['💯', 'cien perfecto'],
      ['💥', 'explosión'],
      ['💫', 'estrellas mareo'],
      ['✨', 'brillo estrellas'],
      ['🔥', 'fuego'],
      ['💤', 'dormir'],
      ['💬', 'mensaje conversación'],
    ],
  },
  {
    name: 'Objetos',
    items: [
      ['🎉', 'confeti celebración'],
      ['🎊', 'fiesta confeti'],
      ['🎈', 'globo cumpleaños'],
      ['🎁', 'regalo'],
      ['🏆', 'trofeo logro'],
      ['🥇', 'medalla primero'],
      ['🎯', 'objetivo meta'],
      ['🚀', 'cohete lanzamiento'],
      ['💻', 'computadora laptop código'],
      ['🖥️', 'monitor pantalla'],
      ['📱', 'teléfono móvil'],
      ['⌨️', 'teclado'],
      ['🛠️', 'herramientas arreglo fix'],
      ['⚙️', 'configuración engrane'],
      ['🐛', 'bug error'],
      ['🔧', 'llave reparar'],
      ['💡', 'idea foco'],
      ['🔍', 'buscar lupa'],
      ['🔒', 'candado seguridad'],
      ['🔑', 'llave acceso'],
      ['📌', 'pin importante'],
      ['📎', 'adjunto clip'],
      ['📝', 'nota escribir'],
      ['📚', 'libros documentación'],
      ['📅', 'calendario fecha'],
      ['⏰', 'reloj alarma'],
      ['⌛', 'tiempo espera'],
      ['✅', 'completado listo check'],
      ['❌', 'cancelar error'],
      ['⚠️', 'advertencia atención'],
      ['❓', 'pregunta'],
      ['❗', 'importante exclamación'],
      ['🟢', 'verde disponible'],
      ['🟡', 'amarillo ausente'],
      ['🔴', 'rojo ocupado'],
      ['☕', 'café pausa'],
      ['🍕', 'pizza'],
      ['🍿', 'palomitas'],
      ['🌈', 'arcoíris'],
      ['🌊', 'ola agua'],
      ['🌞', 'sol día'],
      ['🌙', 'luna noche'],
      ['🌻', 'flor'],
      ['🐈', 'gato'],
      ['🐕', 'perro'],
    ],
  },
] as const;
export const skinTones = ['', '🏻', '🏼', '🏽', '🏾', '🏿'];
export const toneNames = [
  'Predeterminado',
  'Claro',
  'Medio claro',
  'Medio',
  'Medio oscuro',
  'Oscuro',
];
export function emojiWithTone(emoji: string, supported: boolean, tone: number) {
  return supported && tone > 0 ? emoji.replace('\uFE0F', '') + (skinTones[tone] || '') : emoji;
}
export function emojiSearch(value: string) {
  return value
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .toLocaleLowerCase('es');
}
export function emojiDescription(value: string) {
  for (const group of emojiGroups)
    for (const item of group.items)
      if (skinTones.some((_, tone) => emojiWithTone(item[0], item.length > 2, tone) === value))
        return item[1];
  return value;
}
