// <auto-generated />
using System;
using AegiTasks.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AegiTasks.Api.Data.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260924151814_ProjectLabels")]
    partial class ProjectLabels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AegiTasks.Api.Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.AppRole", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.HasKey("Name");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.FocusProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Animated")
                        .HasColumnType("boolean");

                    b.Property<int>("Cycles")
                        .HasColumnType("integer");

                    b.Property<int>("FocusMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("LongBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ShortBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("Sound")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("FocusProfiles");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.FocusSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedCycles")
                        .HasColumnType("integer");

                    b.Property<int>("Cycles")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FocusMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LongBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RemainingSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("ShortBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"FinishedAt\" IS NULL");

                    b.ToTable("FocusSessions");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Font")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LinkedTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)");

                    b.Property<bool>("Pinned")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FolderId", "SpaceId");

                    b.HasIndex("ProjectId", "SpaceId");

                    b.HasIndex("SpaceId", "FolderId", "Archived");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.NoteFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.HasIndex("ParentId", "SpaceId");

                    b.ToTable("NoteFolders");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.PagePermission", b =>
                {
                    b.Property<string>("RoleName")
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Page")
                        .HasColumnType("text");

                    b.Property<bool>("Allowed")
                        .HasColumnType("boolean");

                    b.HasKey("RoleName", "Page");

                    b.ToTable("PagePermissions");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InviteExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteHash")
                        .HasColumnType("text");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasFilter("\"IsPersonal\" = TRUE");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.SpaceMember", b =>
                {
                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SpaceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SpaceMembers");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.TaskStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SessionVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int?>("EstimateMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("FolderId", "ProjectId");

                    b.HasIndex("StatusId", "ProjectId");

                    b.HasIndex("ProjectId", "Archived", "StatusId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WorkItemTags", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid");

                    b.HasKey("TagsId", "WorkItemId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("WorkItemTags");
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Activity", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegiTasks.Api.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Attachment", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegiTasks.Api.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.FocusProfile", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.User", null)
                        .WithOne()
                        .HasForeignKey("AegiTasks.Api.Domain.FocusProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.FocusSession", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Folder", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Note", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.Space", null)
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegiTasks.Api.Domain.NoteFolder", null)
                        .WithMany()
                        .HasForeignKey("FolderId", "SpaceId")
                        .HasPrincipalKey("Id", "SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AegiTasks.Api.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "SpaceId")
                        .HasPrincipalKey("Id", "SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.NoteFolder", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.Space", null)
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegiTasks.Api.Domain.NoteFolder", null)
                        .WithMany()
                        .HasForeignKey("ParentId", "SpaceId")
                        .HasPrincipalKey("Id", "SpaceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.PagePermission", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Project", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.Space", null)
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Space", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.SpaceMember", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.Space", null)
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AegiTasks.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.Tag", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.Space", null)
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.TaskStatus", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.User", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.AppRole", null)
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AegiTasks.Api.Domain.WorkItem", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AegiTasks.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegiTasks.Api.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AegiTasks.Api.Domain.Folder", null)
                        .WithMany()
                        .HasForeignKey("FolderId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AegiTasks.Api.Domain.TaskStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkItemTags", b =>
                {
                    b.HasOne("AegiTasks.Api.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AegiTasks.Api.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
